export const REGISTER_DEFAULT_VALUES = {
  empId: 0,
  userId: 0,
  firstName: '',
  middleName: '',
  lastName: '',
  email: '',
  altEmail: '',
  mobileNo: '',
  dateOfBirth: '',
  nationalId: '',
  nationalityId: '0',
  genderId: '0',
  mStatusId: '0',
  bloodGrpId: '0',
  religionId: '0',
  eContPerson: '',
  eContNo: '',
  relationId: '0',
  photo: '',
  postedBy: 0,
  address: {
    primary: {
      id: null,
      sCode: '0',
      dCode: '0',
      pCode: '0',
      city: '',
      street: '',
      contactNo: '',
      addressTypeId: 1,
    },
    temporary: {
      id: null,

      sCode: '0',
      dCode: '0',
      pCode: '0',
      city: '',
      street: '',
      contactNo: '',
      addressTypeId: 2,
    },
  },
  familyDetail: [
    {
      id: 0,
      name: '',
      relationId: '0',
      occupation: '',
      doB: '',
      contactNo: '',
      nomineeOrder: '0',
    },
  ],
};